version: '3.8'

services:
  # Наша база данных
  db:
    image: postgres:15-alpine
    container_name: goevent_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: goevent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Наш Go-сервис
  app:
    build: .
    container_name: goevent_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: goevent
      JWT_SECRET: super-secret-key
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # Redis для кэширования и Rate Limiting
  redis:
    image: redis:7-alpine
    container_name: goevent_redis
    ports:
      - "6379:6379"

  # Prometheus для сбора метрик
  prometheus:
    image: prom/prometheus:latest
    container_name: goevent_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  # Grafana для визуализации
  grafana:
    image: grafana/grafana:latest
    container_name: goevent_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data: