basePath: /
definitions:
  entity.Event:
    properties:
      created_at:
        type: string
      creator_id:
        type: integer
      date:
        type: string
      description:
        type: string
      id:
        type: integer
      location:
        type: string
      max_participants:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  handler.createEventInput:
    properties:
      date:
        description: В формате RFC3339
        type: string
      description:
        type: string
      location:
        type: string
      max_participants:
        type: integer
      title:
        type: string
    required:
    - date
    - title
    type: object
  handler.signInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handler.signUpInput:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for GoEvent Application
  title: GoEvent API
  version: "1.0"
paths:
  /api/v1/events:
    get:
      consumes:
      - application/json
      description: get list of events
      parameters:
      - default: 10
        description: limit
        in: query
        name: limit
        type: integer
      - default: 0
        description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Event'
            type: array
      summary: List Events
      tags:
      - events
    post:
      consumes:
      - application/json
      description: create a new event
      parameters:
      - description: event info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.createEventInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      security:
      - ApiKeyAuth: []
      summary: Create Event
      tags:
      - events
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
      summary: Sign In
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signUpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Sign Up
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
